### ISSUE TITLE
Adding a License

### ISSUE THREAD

**Issue by ALITHEALI** [mpkelly/react-editor-kit#1]
Hey! Thanks for this great project. I was wondering if you can add a license to this project so that if it is an open source I can use it in my commercial project? Thanks in advance.

**Comment by mpkelly** [comment]
Hi @ALITHEALI, 

I am in the process of writing docs and examples. I am going to make the project private until that's complete, however, if you want to use it then download/fork it now and I will hold off making it private until this evening (Bangkok time). I have added a MIT license, too. The code is usable but "beta" and probably wont change much. I just need better docs to make it ready for public consumption. I didn't think anyone would find my project so I left it public!

Thanks
Mike

**Comment by ALITHEALI** [comment]
Hey @mpkelly !
Thanks a lot for licensing it as MIT. By the way, if you make it public later on and you need help with the Docs, or with anything on this project, I'm 100% ready to contribute. This is a great project and thanks for bringing it to the community. ❤️

**Comment by mpkelly** [comment]
Thanks @ALITHEALI , will be sure to keep you posted.
